//
// This source file is part of the Stanford Biodesign Digital Health Spezi Web Design System open-source project
//
// SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // Sidebar for regular documentation
  docsSidebar: [{ type: "autogenerated", dirName: "docs" }],

  // Sidebar for API Reference (auto-generated by TypeDoc)
  apiSidebar: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
