import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // Sidebar for regular documentation
  docsSidebar: [{ type: "autogenerated", dirName: "docs" }],

  // Sidebar for API Reference (auto-generated by TypeDoc)
  apiSidebar: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
